package crawler.view;

import javax.swing.*;
import java.awt.*;

public class Settings {
    private JTextField UrlTextField;
    private JButton runButton;
    private JTextField textField2;
    private JPanel SettingsPanel;
    private JTextField textField1;
    private JCheckBox enabledCheckBox;
    private JTextField textField3;
    private JCheckBox enabledCheckBox1;
    private JTextField textField4;
    private JButton saveButton;

    public JPanel getSettingsPanel() {
        return SettingsPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        SettingsPanel = new JPanel();
        SettingsPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Start URL:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(2, 2, 2, 2);
        SettingsPanel.add(label1, gbc);
        UrlTextField = new JTextField();
        UrlTextField.setColumns(20);
        UrlTextField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 7.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(2, 5, 2, 2);
        SettingsPanel.add(UrlTextField, gbc);
        runButton = new JButton();
        runButton.setText("Run");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 5);
        SettingsPanel.add(runButton, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Workers:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(2, 2, 2, 2);
        SettingsPanel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Maximum depth:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(2, 2, 2, 2);
        SettingsPanel.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Time Limit:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(2, 2, 2, 2);
        SettingsPanel.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Elapsed Time:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(2, 2, 2, 2);
        SettingsPanel.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Parsed pages:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(2, 2, 2, 2);
        SettingsPanel.add(label6, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Export:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(2, 2, 2, 2);
        SettingsPanel.add(label7, gbc);
        textField2 = new JTextField();
        textField2.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(2, 5, 2, 5);
        SettingsPanel.add(textField2, gbc);
        textField1 = new JTextField();
        textField1.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 0);
        SettingsPanel.add(textField1, gbc);
        enabledCheckBox = new JCheckBox();
        enabledCheckBox.setText("Enabled");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 5, 0, 5);
        SettingsPanel.add(enabledCheckBox, gbc);
        textField3 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 0);
        SettingsPanel.add(textField3, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Seconds");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        SettingsPanel.add(label8, gbc);
        enabledCheckBox1 = new JCheckBox();
        enabledCheckBox1.setText("Enabled");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 5, 0, 5);
        SettingsPanel.add(enabledCheckBox1, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("0:00");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 5, 0, 0);
        SettingsPanel.add(label9, gbc);
        final JLabel label10 = new JLabel();
        label10.setText("0");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 5, 0, 0);
        SettingsPanel.add(label10, gbc);
        textField4 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 0);
        SettingsPanel.add(textField4, gbc);
        saveButton = new JButton();
        saveButton.setText("Save");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 5);
        SettingsPanel.add(saveButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return SettingsPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
