package crawler.view;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import static java.lang.System.Logger.Level.INFO;

public class Settings {
    private static final System.Logger LOGGER = System.getLogger("");

    private JTextField UrlTextField;
    private JToggleButton runButton;
    private JTextField textField2;
    private JPanel settingsPanel;
    private JTextField DepthTextField;
    private JCheckBox enabledCheckBox;
    private JTextField textField3;
    private JCheckBox enabledCheckBox1;
    private JTextField textField4;
    private JButton saveButton;


    public Settings() {
        runButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                LOGGER.log(INFO, "actionPerformed: {0}", e.getActionCommand());
            }
        });
    }

    public JPanel getSettingsPanel() {
        return settingsPanel;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        settingsPanel = new JPanel();
        settingsPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Start URL:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 2, 2);
        settingsPanel.add(label1, gbc);
        UrlTextField = new JTextField();
        UrlTextField.setColumns(20);
        UrlTextField.setName("UrlTextField");
        UrlTextField.setText("");
        UrlTextField.setToolTipText("for entering a URL");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 2, 2);
        settingsPanel.add(UrlTextField, gbc);
        runButton = new JToggleButton();
        runButton.setName("RunButton");
        runButton.setText("Run");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 0, 5);
        settingsPanel.add(runButton, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Workers:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(2, 5, 2, 2);
        settingsPanel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Maximum depth:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(2, 5, 2, 2);
        settingsPanel.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Time Limit:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(2, 5, 2, 2);
        settingsPanel.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Elapsed Time:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(2, 5, 2, 2);
        settingsPanel.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Parsed pages:");
        label6.setToolTipText("the number of parsed pages");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(2, 5, 2, 2);
        settingsPanel.add(label6, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Export:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(2, 5, 5, 2);
        settingsPanel.add(label7, gbc);
        textField2 = new JTextField();
        textField2.setText("");
        textField2.setToolTipText("specifying the number of thread-workers to be created");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(2, 5, 2, 5);
        settingsPanel.add(textField2, gbc);
        DepthTextField = new JTextField();
        DepthTextField.setName("DepthTextField");
        DepthTextField.setText("");
        DepthTextField.setToolTipText("specify the maximum depth");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 0);
        settingsPanel.add(DepthTextField, gbc);
        enabledCheckBox = new JCheckBox();
        enabledCheckBox.setName("DepthCheckBox");
        enabledCheckBox.setText("Enabled");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 5, 0, 5);
        settingsPanel.add(enabledCheckBox, gbc);
        textField3 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 0);
        settingsPanel.add(textField3, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Seconds");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        settingsPanel.add(label8, gbc);
        enabledCheckBox1 = new JCheckBox();
        enabledCheckBox1.setText("Enabled");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 5, 0, 5);
        settingsPanel.add(enabledCheckBox1, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("0:00");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 5, 0, 0);
        settingsPanel.add(label9, gbc);
        final JLabel label10 = new JLabel();
        label10.setName("ParsedLabel");
        label10.setText("0");
        label10.setToolTipText("the number of parsed pages");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 5, 0, 0);
        settingsPanel.add(label10, gbc);
        textField4 = new JTextField();
        textField4.setName("ExportUrlTextField");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 5, 0);
        settingsPanel.add(textField4, gbc);
        saveButton = new JButton();
        saveButton.setName("ExportButton");
        saveButton.setText("Save");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 5, 5);
        settingsPanel.add(saveButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return settingsPanel;
    }

}
